version: "3.8"

services:
  api:
    build: .
    container_name: housing-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MODEL_PATH=models/ridge_model.pkl
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

  mlflow:
    image: python:3.10-slim
    container_name: mlflow-server
    working_dir: /app
    ports:
      - "5555:5555"
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlflow_data:/app/data
    command: >
      sh -c "pip install mlflow && python -m mlflow server --backend-store-uri sqlite:///data/mlflow.db --default-artifact-root /app/mlruns --host 0.0.0.0 --port 5555"

volumes:
  grafana-storage:
