name: CI/CD Pipeline

on:
  push:
    branches: [main]
    paths:
      - "**.py"
      - "data/**" # Added: Trigger on new/changed data
      - "requirements.txt"
  pull_request:
    branches: [main]
  workflow_dispatch: # Added: Manual trigger option

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip" # Cache pip packages

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t niranjanjoshi14/housing-api:latest .

      - name: Push Docker image
        run: docker push niranjanjoshi14/housing-api:latest

      - name: Check .gitignore to avoid large files
        run: |
          echo "Checking for unwanted files in repo..."
          test ! -d .mlruns || (echo ".mlruns found, please add to .gitignore" && exit 1)
          test ! -d venv || (echo "venv found, please add to .gitignore" && exit 1)
          test ! -d src/__pycache__ || (echo "__pycache__ found, please add to .gitignore" && exit 1)

      - name: Run training
        run: |
          python src/train.py

      - name: Save trained model artifact
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: models/latest_model.pkl

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q || echo "No tests found"

      - name: Build Docker image with model
        run: |
          docker build -t housing-api .

      - name: Push Docker image with model
        run: docker push housing-api:latest
